/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionMenu: typeof import('./src/components/project/ActionMenu.vue')['default']
    CardInvitation: typeof import('./src/components/invitation/CardInvitation.vue')['default']
    CardProject: typeof import('./src/components/project/CardProject.vue')['default']
    Dashboar: typeof import('./src/components/Dashboar.vue')['default']
    DashBoard: typeof import('./src/components/details/dashBoard.vue')['default']
    DetAils: typeof import('./src/components/details/detAils.vue')['default']
    FormCreateProject: typeof import('./src/components/project/FormCreateProject.vue')['default']
    KanBan: typeof import('./src/components/details/kanBan.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./src/components/details/TaskCard.vue')['default']
  }
}
